services:
  grafana:
    # Point Grafana at the renderer sidecar
    environment:
      - GF_RENDERING_MODE=clustered
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
      - GF_DATE_FORMATS_DEFAULT_TIMEZONE=UTC
    depends_on:
      - renderer

  # Headless Chromium renderer for PNG export
  renderer:
    image: grafana/grafana-image-renderer:3.11.0
    restart: unless-stopped
    shm_size: 1g
    environment:
      - ENABLE_METRICS=true
      - RENDERING_VERBOSE_LOGGING=true
      - IGNORE_HTTPS_ERRORS=true
      - CHROME_ARGS=--no-sandbox,--disable-dev-shm-usage
    # no ports: Grafana talks to it over the compose network
