pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Spin up stack') {
      steps { sh 'docker compose up -d httpbin grafana prometheus loki promtail' }
    }
    stage('Perf Smoke') {
      steps { sh './scripts/run_local.sh load' }
    }
    stage('Archive Reports') {
      steps { archiveArtifacts artifacts: 'reports/**', fingerprint: true }
    }
  }
}
