apiVersion: 1
datasources:
  - name: InfluxDB-jmeter
    type: influxdb
    uid: influxdb
    access: proxy
    url: http://influxdb:8086
    database: jmeter
    isDefault: true
    jsonData:
      version: InfluxQL
      httpMode: POST

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
