apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  type: {{ .Values.service.type }}
  selector: { app: httpbin }
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80