image:
  repository: kennethreitz/httpbin
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  host: httpbin.local
  annotations: {}
