global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Example: scrape node exporter if you add one
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
