name: perf-smoke

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  jmeter-smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      # Pull your repo into the runner
        uses: actions/checkout@v4

      - name: Start minimal infra (httpbin + monitoring)
        run: |
          set -eux
          # Bring up only what we need for a smoke perf run
          docker compose up -d influxdb httpbin grafana loki promtail prometheus cadvisor
          # brief wait so services are listening
          sleep 15
          docker ps

      - name: Build JMeter image (5.6.3)
        run: docker build -t jmeter:5.6.3 ./jmeter/docker

      - name: Run smoke test (write JTL + jmeter.log with header/standard columns)
        run: |
          set -euxo pipefail

          # Clean previous outputs so the JTL isn't appended to an old file
          rm -rf jmeter/results/smoke jmeter/results/smoke.jtl || true
          mkdir -p jmeter/results/smoke/html

          # Use host networking so JMeter can hit httpbin exposed on 8080
          docker run --rm --network host \
            -v "$GITHUB_WORKSPACE/jmeter:/jmeter" -w /jmeter jmeter:5.6.3 \
            -q config/user.properties \
            # --- force CSV with header + the standard 17 fields (prevents column mismatch) ---
            -Jjmeter.save.saveservice.output_format=csv \
            -Jjmeter.save.saveservice.print_field_names=true \
            -Jjmeter.save.saveservice.default_delimiter=, \
            -Jjmeter.save.saveservice.timestamp_format=ms \
            -Jjmeter.save.saveservice.data_type=true \
            -Jjmeter.save.saveservice.label=true \
            -Jjmeter.save.saveservice.response_code=true \
            -Jjmeter.save.saveservice.response_message=true \
            -Jjmeter.save.saveservice.thread_name=true \
            -Jjmeter.save.saveservice.successful=true \
            -Jjmeter.save.saveservice.failure_message=true \
            -Jjmeter.save.saveservice.bytes=true \
            -Jjmeter.save.saveservice.sent_bytes=true \
            -Jjmeter.save.saveservice.grp_threads=true \
            -Jjmeter.save.saveservice.all_threads=true \
            -Jjmeter.save.saveservice.URL=true \
            -Jjmeter.save.saveservice.latency=true \
            -Jjmeter.save.saveservice.idle_time=true \
            -Jjmeter.save.saveservice.connect_time=true \
            # --- your test plan + runtime knobs ---
            -n -t testplans/httpbin_load.jmx \
            -Jthreads=50 -Jrampup=30 -Jduration=60 \
            -Jtarget_host=localhost -Jtarget_port=8080 \
            # --- output files ---
            -l results/smoke.jtl \
            -j results/smoke/jmeter.log

          # Show first two lines so we can prove the header exists (visible in job logs)
          head -n 2 jmeter/results/smoke.jtl || true

      - name: Generate HTML report
        run: |
          set -eux
          docker run --rm --network host \
            -v "$GITHUB_WORKSPACE/jmeter:/jmeter" -w /jmeter jmeter:5.6.3 \
            -g results/smoke.jtl -o results/smoke/html
          ls -R jmeter/results/smoke

      - name: Upload JMeter artifacts (HTML + JTL + jmeter.log)
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-smoke-artifacts
          if-no-files-found: error
          path: |
            jmeter/results/smoke/html
            jmeter/results/smoke.jtl
            jmeter/results/smoke/jmeter.log

      - name: Stop stack
        if: always()
        run: docker compose down -v
