name: perf-suite

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  jmeter-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - scenario: smoke
            threads: 50
            rampup: 30
            duration: 60
          - scenario: load
            threads: 100
            rampup: 60
            duration: 180
          - scenario: stress
            threads: 300
            rampup: 60
            duration: 120
          - scenario: spike
            threads: 200
            rampup: 10
            duration: 60
          - scenario: soak
            threads: 50
            rampup: 30
            duration: 300

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start minimal infra (httpbin + monitoring)
        run: |
          set -eux
          # assumes your docker-compose has grafana, renderer, prometheus, cadvisor, etc.
          docker compose up -d influxdb httpbin grafana renderer loki promtail prometheus cadvisor
          # give services time to come up
          for i in {1..30}; do
            docker ps
            curl -fsS http://localhost:3000/api/health >/dev/null && break || sleep 2
          done

      - name: Build JMeter image (5.6.3)
        run: docker build -t jmeter:5.6.3 ./jmeter/docker

      # ---- Run test, write CSV JTL (17 columns + header), and build dashboard in one go ----
      - name: Run ${{ matrix.scenario }} (headless; CSV JTL; generate HTML)
        run: |
          set -eux
          SCEN=${{ matrix.scenario }}
          ROOT=jmeter/results
          OUT="$ROOT/$SCEN"
          CSV_JTL="$ROOT/${SCEN}.csv"

          mkdir -p "$OUT"
          rm -f "$CSV_JTL" || true
          rm -rf "$OUT/html" || true

          # Force the standard CSV layout the HTML report expects (17 columns + header).
          set +e
          docker run --rm --network host \
            -e JVM_ARGS="-Djava.awt.headless=true -Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m" \
            -v "$GITHUB_WORKSPACE/jmeter:/jmeter" -w /jmeter jmeter:5.6.3 \
            -n -t testplans/httpbin_load.jmx \
            -Jthreads=${{ matrix.threads }} \
            -Jrampup=${{ matrix.rampup }} \
            -Jduration=${{ matrix.duration }} \
            -Jscenario_name=$SCEN \
            -Jtarget_host=localhost -Jtarget_port=8080 \
            -Jjmeter.save.saveservice.output_format=csv \
            -Jjmeter.save.saveservice.print_field_names=true \
            -Jjmeter.save.saveservice.default_delimiter=, \
            -Jjmeter.save.saveservice.timestamp_format=ms \
            -Jjmeter.save.saveservice.data_type=true \
            -Jjmeter.save.saveservice.label=true \
            -Jjmeter.save.saveservice.response_code=true \
            -Jjmeter.save.saveservice.response_message=true \
            -Jjmeter.save.saveservice.thread_name=true \
            -Jjmeter.save.saveservice.successful=true \
            -Jjmeter.save.saveservice.failure_message=true \
            -Jjmeter.save.saveservice.bytes=true \
            -Jjmeter.save.saveservice.sent_bytes=true \
            -Jjmeter.save.saveservice.grp_threads=true \
            -Jjmeter.save.saveservice.all_threads=true \
            -Jjmeter.save.saveservice.url=true \
            -Jjmeter.save.saveservice.latency=true \
            -Jjmeter.save.saveservice.idle_time=true \
            -Jjmeter.save.saveservice.connect_time=true \
            -l "results/${SCEN}.csv" \
            -j "results/${SCEN}/jmeter.log" \
            -e -o "results/${SCEN}/html"
          EXIT=$?
          set -e

          echo "JMeter raw exit code (info only): $EXIT"
          echo "CSV header:"; head -n 1 "$CSV_JTL" || true
          test -f "$OUT/html/index.html" && echo "Dashboard generated." || echo "Dashboard missing."
          ls -l "$ROOT" || true; ls -l "$OUT" || true

      # ---- Render Grafana PNGs (AFTER the test), then upload one artifact per scenario ----
      - name: Render Grafana panels (${{ matrix.scenario }})
        if: always()
        run: |
          set -eux
          SCEN=${{ matrix.scenario }}
          RAMP=${{ matrix.rampup }}
          DUR=${{ matrix.duration }}
          RANGE=$((RAMP + DUR + 120))   # seconds back from now
          TO_ms=$(( $(date -u +%s) * 1000 ))
          FROM_ms=$(( $(date -u -d "-${RANGE} seconds" +%s) * 1000 ))
          OUT_DIR="jmeter/results/${SCEN}/grafana"
          mkdir -p "${OUT_DIR}"

          # basic auth (from docker-compose env GF_SECURITY_ADMIN_USER/PASSWORD)
          AUTH_FLAG="-u admin:admin"

          # Resolve JMeter dashboard UID (fallback if jq/file missing)
          JM_DASH_UID=$(jq -r '.uid // .dashboard.uid' grafana/dashboards/jmeter-overview.json 2>/dev/null || echo "jmeter-overview")

          echo "Available panels (id: title) for UID=${JM_DASH_UID}:"
          curl -fsSL ${AUTH_FLAG} "http://localhost:3000/api/dashboards/uid/${JM_DASH_UID}" \
            | jq -r '.dashboard.panels[] | "\(.id): \(.title)"' || true

          # Panel IDs – adjust after first run if needed
          RPS_ID=${RPS_ID:-2}
          ERR_ID=${ERR_ID:-4}
          LAT_ID=${LAT_ID:-3}

          render() {
            local id="$1" out="$2"
            curl -fsSL ${AUTH_FLAG} \
              "http://localhost:3000/render/d-solo/${JM_DASH_UID}?orgId=1&panelId=${id}&from=${FROM_ms}&to=${TO_ms}&width=1600&height=800&tz=UTC&theme=dark" \
              -o "${out}" || true
          }

          render "${RPS_ID}" "${OUT_DIR}/requests_per_second.png"
          render "${ERR_ID}" "${OUT_DIR}/error_percent.png"
          render "${LAT_ID}" "${OUT_DIR}/latency.png"
          ls -l "${OUT_DIR}" || true

      - name: Upload artifacts (${{ matrix.scenario }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # unique per scenario & run to avoid 409 conflicts on re-runs
          name: jmeter-${{ matrix.scenario }}-${{ github.run_id }}-${{ github.run_attempt }}
          retention-days: 30
          if-no-files-found: warn
          path: |
            jmeter/results/${{ matrix.scenario }}/html
            jmeter/results/${{ matrix.scenario }}.csv
            jmeter/results/${{ matrix.scenario }}/jmeter.log
            jmeter/results/${{ matrix.scenario }}/grafana

      - name: Stop stack
        if: always()
        run: docker compose down -v
