services:
  grafana:
    image: grafana/grafana:10.4.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_ROOT_URL: http://localhost:3000/
      # >>> crucial: wire renderer
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_RENDERING_CONCURRENT_RENDER_REQUEST_LIMIT: "4"
      GF_LOG_FILTERS: rendering:debug
    depends_on:
      - renderer
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

  renderer:
    image: grafana/grafana-image-renderer:3.6.1
    container_name: renderer
    # No host port needed; Grafana talks to it via the compose network
    environment:
      ENABLE_METRICS: "true"
      LOG_LEVEL: debug
      RENDERING_MODE: clustered
    restart: unless-stopped
